import type { Opportunity } from "@/lib/domain";

export const demoOpportunities: Opportunity[] = [
  {
    id: "demo-northstar-software",
    slug: "demo-northstar-software",
    company: "Northstar Labs (fictional)",
    title: "Software Engineering Intern",
    description: "Build TypeScript and SQL tools that help student research teams work with open data.",
    eligibleClassYears: ["freshman", "sophomore"],
    eligibilityBasis: "listed_years",
    eligibilityNotes: "The fictional source names first- and second-year students.",
    location: "Boston, MA",
    workMode: "hybrid",
    compensationType: "paid",
    compensationDetails: "$28/hour (fictional)",
    sourceUrl: "https://example.org/demo/northstar-software",
    canonicalSourceId: "demo-northstar-software",
    deadlineDate: "2026-11-14",
    deadlineAt: null,
    deadlineType: "date_only",
    sourcePostedDate: null,
    lastVerifiedAt: "2026-09-30T12:00:00Z",
    status: "published",
    isDemo: true,
    createdAt: "2026-09-22T12:00:00Z",
  },
  {
    id: "demo-fieldnote-research",
    slug: "demo-fieldnote-research",
    company: "Fieldnote (fictional)",
    title: "Data Research Intern",
    description: "Use Python to clean survey datasets and summarize findings for an education research team.",
    eligibleClassYears: [],
    eligibilityBasis: "undergraduates",
    eligibilityNotes: "The fictional source says enrolled undergraduate students; it does not name individual class years.",
    location: "Remote, US",
    workMode: "remote",
    compensationType: "unknown",
    compensationDetails: null,
    sourceUrl: "https://example.org/demo/fieldnote-research",
    canonicalSourceId: "demo-fieldnote-research",
    deadlineDate: "2026-12-02",
    deadlineAt: null,
    deadlineType: "date_only",
    sourcePostedDate: null,
    lastVerifiedAt: "2026-09-29T15:00:00Z",
    status: "published",
    isDemo: true,
    createdAt: "2026-09-21T12:00:00Z",
  },
  {
    id: "demo-juniper-design",
    slug: "demo-juniper-design",
    company: "Juniper Studio (fictional)",
    title: "Product Design Intern",
    description: "Prototype accessible tools, interview users, and share design explorations with a small product team.",
    eligibleClassYears: [],
    eligibilityBasis: "unclear",
    eligibilityNotes: "The fictional source does not state whether first- or second-year students may apply.",
    location: "New York, NY",
    workMode: "hybrid",
    compensationType: "paid",
    compensationDetails: "$24/hour (fictional)",
    sourceUrl: "https://example.org/demo/juniper-design",
    canonicalSourceId: "demo-juniper-design",
    deadlineDate: null,
    deadlineAt: null,
    deadlineType: "unknown",
    sourcePostedDate: null,
    lastVerifiedAt: "2026-09-27T09:00:00Z",
    status: "published",
    isDemo: true,
    createdAt: "2026-09-19T12:00:00Z",
  },
  {
    id: "demo-copperfield-mechanical",
    slug: "demo-copperfield-mechanical",
    company: "Copperfield Robotics (fictional)",
    title: "Mechanical Engineering Intern",
    description: "Test robotic prototypes and document design changes with the hardware team.",
    eligibleClassYears: ["junior", "senior"],
    eligibilityBasis: "listed_years",
    eligibilityNotes: "The fictional source names third- and fourth-year students.",
    location: "Detroit, MI",
    workMode: "onsite",
    compensationType: "paid",
    compensationDetails: "$25/hour (fictional)",
    sourceUrl: "https://example.org/demo/copperfield-mechanical",
    canonicalSourceId: "demo-copperfield-mechanical",
    deadlineDate: "2026-10-28",
    deadlineAt: null,
    deadlineType: "date_only",
    sourcePostedDate: null,
    lastVerifiedAt: "2026-09-25T11:00:00Z",
    status: "published",
    isDemo: true,
    createdAt: "2026-09-17T12:00:00Z",
  },
];